remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: U-PHAIN-TF
description: Audio Inpainting in Time-Frequency Domain with Phase-Aware Prior
